build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related qa APIs "
  contactDetails:
    name: "John - QA Lead"
    email: "john@bank.com"
  onCallSupport:
    - (91) 9876543210
    - (91) 9876543210
