build:
  version: "3.0"

accounts:
  message: "Welcome to Bank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bank.com"
  onCallSupport:
    - (91) 9876543210
    - (91) 9876543210
