build:
  version: "3.0"

cards:
  message: "Welcome to Bank cards related local APIs "
  contactDetails:
    name: "John - Developer"
    email: "john@bank.com"
  onCallSupport:
    - (91) 9876543210
    - (91) 9876543210
