build:
  version: "3.0"

loans:
  message: "Welcome to Bank loans related prod APIs "
  contactDetails:
    name: "John - Product Owner"
    email: "john@bank.com"
  onCallSupport:
    - (91) 9876543210
    - (91) 9876543210
